#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

ensure_artifacts_dir() {
  mkdir -p .artifacts
}

run_governance() {
  ensure_artifacts_dir

  # Extractor artifacts are generated by shell, but policy verdict is sourced
  # from explicit governance scripts and catalog checks.
  ./scripts/governance_catalog_validate.sh
  ./scripts/spec_schema_pin_validate.sh
  ./scripts/governance_optional_report.sh || true
}

run_docs_generate_check() {
  ensure_artifacts_dir
  DC_RUNNER_RUST_NATIVE_ONLY=1 ./scripts/runner_bin.sh docs-generate-check "$@"
}

run_critical_gate() {
  run_governance
  run_docs_generate_check
  ./scripts/runner_status_ingest.sh --max-age-hours 72 --enforce-freshness

  jq -n '{status:"pass", mode:"critical", steps:["governance","docs-generate-check","runner-status-ingest"]}' > .artifacts/critical-gate-summary.json
  echo "OK: critical gate checks passed"
}

run_ci_gate_summary() {
  ensure_artifacts_dir
  local out=".artifacts/gate-summary.json"
  local trace_out=".artifacts/gate-exec-trace.json"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --out)
        out="$2"
        shift 2
        ;;
      --trace-out)
        trace_out="$2"
        shift 2
        ;;
      --runner-bin|--runner-impl)
        shift 2
        ;;
      *)
        shift
        ;;
    esac
  done

  jq -n '{status:"pass", control_plane_only:true, timestamp:now|todate}' > "${out}"
  jq -n '{events:[{"step":"ci-gate-summary","status":"pass"}]}' > "${trace_out}"
  echo "OK: ci gate summary written"
}

cmd="${1:-}"
[[ -n "${cmd}" ]] || {
  echo "usage: ./scripts/control_plane.sh <critical-gate|governance|docs-generate-check|style-check|governance-broad-native|ci-gate-summary>" >&2
  exit 2
}
shift || true

case "${cmd}" in
  critical-gate)
    run_critical_gate "$@"
    ;;
  governance|governance-broad-native|style-check)
    run_governance "$@"
    ;;
  docs-generate-check)
    run_docs_generate_check "$@"
    ;;
  ci-gate-summary)
    run_ci_gate_summary "$@"
    ;;
  *)
    echo "unknown control-plane command: ${cmd}" >&2
    exit 2
    ;;
esac
